name: Build and Deploy
on: [push, workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Package Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build Package
        run: npm run build
      - name: Install Example Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd example
          npm install
      - name: Build Example
        env:
          REACT_APP_ARCGIS_APIKEY: ${{ secrets.REACT_APP_ARCGIS_APIKEY }}
        run: |
          cd example
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: example/build # The folder the action should deploy.
